kind: pipeline
name: default

steps:

- name: maven-library-build
  image: maven:3.6-jdk-8
  commands:
    - mvn clean package #-P MavenCentral
    - cd ./target/
    - ls -lisa
  volumes:
  - name: maven-cache
    path: /root/.m2

- name: gradlew-library-build
  image: openjdk:8-jdk
  commands:
    - ./gradlew --no-daemon -b build.gradle clean buildResources :javaBuild:defaultJar
    - ls -lisa ./legacyJava/java7/build/libs/
    - ls -lisa ./java8/build/libs/
    - ls -lisa ./java11/build/libs/
  volumes:
  - name: maven-cache
    path: /root/.m2


volumes:
  - name: maven-cache
    host: 
      path: /temp/drone/m2cache