/*
 ========================================================================
 Bootstrap: scrollspy.js v3.4.1
 https://getbootstrap.com/docs/3.4/javascript/#scrollspy
 ========================================================================
 Copyright 2011-2019 Twitter, Inc.
 Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 ======================================================================== */
var process=process||{env:{NODE_ENV:"development"}};
+function(b){function e(a,f){this.$body=b(document.body);this.$scrollElement=b(a).is(document.body)?b(window):b(a);this.options=b.extend({},e.DEFAULTS,f);this.selector=(this.options.target||"")+" .nav li > a";this.offsets=[];this.targets=[];this.activeTarget=null;this.scrollHeight=0;this.$scrollElement.on("scroll.bs.scrollspy",b.proxy(this.process,this));this.refresh();this.process()}function l(a){return this.each(function(){var f=b(this),h=f.data("bs.scrollspy"),c="object"==typeof a&&a;h||f.data("bs.scrollspy",
h=new e(this,c));if("string"==typeof a)h[a]()})}e.VERSION="3.4.1";e.DEFAULTS={offset:10};e.prototype.getScrollHeight=function(){return this.$scrollElement[0].scrollHeight||Math.max(this.$body[0].scrollHeight,document.documentElement.scrollHeight)};e.prototype.refresh=function(){var a=this,f="offset",h=0;this.offsets=[];this.targets=[];this.scrollHeight=this.getScrollHeight();b.isWindow(this.$scrollElement[0])||(f="position",h=this.$scrollElement.scrollTop());this.$body.find(this.selector).map(function(){var c=
b(this);c=c.data("target")||c.attr("href");var d=/^#./.test(c)&&b(c);return d&&d.length&&d.is(":visible")&&[[d[f]().top+h,c]]||null}).sort(function(c,d){return c[0]-d[0]}).each(function(){a.offsets.push(this[0]);a.targets.push(this[1])})};e.prototype.process=function(){var a=this.$scrollElement.scrollTop()+this.options.offset,f=this.getScrollHeight(),h=this.options.offset+f-this.$scrollElement.height(),c=this.offsets,d=this.targets,k=this.activeTarget,g;this.scrollHeight!=f&&this.refresh();if(a>=
h)return k!=(g=d[d.length-1])&&this.activate(g);if(k&&a<c[0])return this.activeTarget=null,this.clear();for(g=c.length;g--;)k!=d[g]&&a>=c[g]&&(void 0===c[g+1]||a<c[g+1])&&this.activate(d[g])};e.prototype.activate=function(a){this.activeTarget=a;this.clear();a=b(this.selector+'[data-target="'+a+'"],'+this.selector+'[href="'+a+'"]').parents("li").addClass("active");a.parent(".dropdown-menu").length&&(a=a.closest("li.dropdown").addClass("active"));a.trigger("activate.bs.scrollspy")};e.prototype.clear=
function(){b(this.selector).parentsUntil(this.options.target,".active").removeClass("active")};var m=b.fn.scrollspy;b.fn.scrollspy=l;b.fn.scrollspy.Constructor=e;b.fn.scrollspy.noConflict=function(){b.fn.scrollspy=m;return this};b(window).on("load.bs.scrollspy.data-api",function(){b('[data-spy="scroll"]').each(function(){var a=b(this);l.call(a,a.data())})})}(jQuery);