/*
 ========================================================================
 Bootstrap: tooltip.js v3.4.1
 https://getbootstrap.com/docs/3.4/javascript/#tooltip
 Inspired by the original jQuery.tipsy by Jason Frame
 ========================================================================
 Copyright 2011-2019 Twitter, Inc.
 Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 ======================================================================== */
var process=process||{env:{NODE_ENV:"development"}};
+function(e){function r(b,a){var c=b.nodeName.toLowerCase();if(-1!==e.inArray(c,a))return-1!==e.inArray(c,t)?!(!b.nodeValue.match(u)&&!b.nodeValue.match(v)):!0;b=e(a).filter(function(h,k){return k instanceof RegExp});a=0;for(var d=b.length;a<d;a++)if(c.match(b[a]))return!0;return!1}function p(b,a,c){if(0===b.length)return b;if(c&&"function"===typeof c)return c(b);if(!document.implementation||!document.implementation.createHTMLDocument)return b;c=document.implementation.createHTMLDocument("sanitization");
c.body.innerHTML=b;b=e.map(a,function(q,w){return w});for(var d=e(c.body).find("*"),h=0,k=d.length;h<k;h++){var g=d[h],l=g.nodeName.toLowerCase();if(-1===e.inArray(l,b))g.parentNode.removeChild(g);else{var m=e.map(g.attributes,function(q){return q});l=[].concat(a["*"]||[],a[l]||[]);for(var n=0,x=m.length;n<x;n++)r(m[n],l)||g.removeAttribute(m[n].nodeName)}}return c.body.innerHTML}var y=["sanitize","whiteList","sanitizeFn"],t="background cite href itemtype longdesc poster src xlink:href".split(" "),
u=/^(?:(?:https?|mailto|ftp|tel|file):|[^&:/?#]*(?:[/?#]|$))/gi,v=/^data:(?:image\/(?:bmp|gif|jpeg|jpg|png|tiff|webp)|video\/(?:mpeg|mp4|ogg|webm)|audio\/(?:mp3|oga|ogg|opus));base64,[a-z0-9+/]+=*$/i,f=function(b,a){this.inState=this.$element=this.hoverState=this.timeout=this.enabled=this.options=this.type=null;this.init("tooltip",b,a)};f.VERSION="3.4.1";f.TRANSITION_DURATION=150;f.DEFAULTS={animation:!0,placement:"top",selector:!1,template:'<div class="tooltip" role="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>',
trigger:"hover focus",title:"",delay:0,html:!1,container:!1,viewport:{selector:"body",padding:0},sanitize:!0,sanitizeFn:null,whiteList:{"*":["class","dir","id","lang","role",/^aria-[\w-]*$/i],a:["target","href","title","rel"],area:[],b:[],br:[],col:[],code:[],div:[],em:[],hr:[],h1:[],h2:[],h3:[],h4:[],h5:[],h6:[],i:[],img:["src","alt","title","width","height"],li:[],ol:[],p:[],pre:[],s:[],small:[],span:[],sub:[],sup:[],strong:[],u:[],ul:[]}};f.prototype.init=function(b,a,c){this.enabled=!0;this.type=
b;this.$element=e(a);this.options=this.getOptions(c);this.$viewport=this.options.viewport&&e(document).find(e.isFunction(this.options.viewport)?this.options.viewport.call(this,this.$element):this.options.viewport.selector||this.options.viewport);this.inState={click:!1,hover:!1,focus:!1};if(this.$element[0]instanceof document.constructor&&!this.options.selector)throw Error("`selector` option must be specified when initializing "+this.type+" on the window.document object!");b=this.options.trigger.split(" ");
for(a=b.length;a--;)if(c=b[a],"click"==c)this.$element.on("click."+this.type,this.options.selector,e.proxy(this.toggle,this));else if("manual"!=c){var d="hover"==c?"mouseleave":"focusout";this.$element.on(("hover"==c?"mouseenter":"focusin")+"."+this.type,this.options.selector,e.proxy(this.enter,this));this.$element.on(d+"."+this.type,this.options.selector,e.proxy(this.leave,this))}this.options.selector?this._options=e.extend({},this.options,{trigger:"manual",selector:""}):this.fixTitle()};f.prototype.getDefaults=
function(){return f.DEFAULTS};f.prototype.getOptions=function(b){var a=this.$element.data(),c;for(c in a)a.hasOwnProperty(c)&&-1!==e.inArray(c,y)&&delete a[c];b=e.extend({},this.getDefaults(),a,b);b.delay&&"number"==typeof b.delay&&(b.delay={show:b.delay,hide:b.delay});b.sanitize&&(b.template=p(b.template,b.whiteList,b.sanitizeFn));return b};f.prototype.getDelegateOptions=function(){var b={},a=this.getDefaults();this._options&&e.each(this._options,function(c,d){a[c]!=d&&(b[c]=d)});return b};f.prototype.enter=
function(b){var a=b instanceof this.constructor?b:e(b.currentTarget).data("bs."+this.type);a||(a=new this.constructor(b.currentTarget,this.getDelegateOptions()),e(b.currentTarget).data("bs."+this.type,a));b instanceof e.Event&&(a.inState["focusin"==b.type?"focus":"hover"]=!0);if(a.tip().hasClass("in")||"in"==a.hoverState)a.hoverState="in";else{clearTimeout(a.timeout);a.hoverState="in";if(!a.options.delay||!a.options.delay.show)return a.show();a.timeout=setTimeout(function(){"in"==a.hoverState&&a.show()},
a.options.delay.show)}};f.prototype.isInStateTrue=function(){for(var b in this.inState)if(this.inState[b])return!0;return!1};f.prototype.leave=function(b){var a=b instanceof this.constructor?b:e(b.currentTarget).data("bs."+this.type);a||(a=new this.constructor(b.currentTarget,this.getDelegateOptions()),e(b.currentTarget).data("bs."+this.type,a));b instanceof e.Event&&(a.inState["focusout"==b.type?"focus":"hover"]=!1);if(!a.isInStateTrue()){clearTimeout(a.timeout);a.hoverState="out";if(!a.options.delay||
!a.options.delay.hide)return a.hide();a.timeout=setTimeout(function(){"out"==a.hoverState&&a.hide()},a.options.delay.hide)}};f.prototype.show=function(){var b=e.Event("show.bs."+this.type);if(this.hasContent()&&this.enabled){this.$element.trigger(b);var a=e.contains(this.$element[0].ownerDocument.documentElement,this.$element[0]);if(!b.isDefaultPrevented()&&a){var c=this;b=this.tip();a=this.getUID(this.type);this.setContent();b.attr("id",a);this.$element.attr("aria-describedby",a);this.options.animation&&
b.addClass("fade");a="function"==typeof this.options.placement?this.options.placement.call(this,b[0],this.$element[0]):this.options.placement;var d=/\s?auto?\s?/i,h=d.test(a);h&&(a=a.replace(d,"")||"top");b.detach().css({top:0,left:0,display:"block"}).addClass(a).data("bs."+this.type,this);this.options.container?b.appendTo(e(document).find(this.options.container)):b.insertAfter(this.$element);this.$element.trigger("inserted.bs."+this.type);d=this.getPosition();var k=b[0].offsetWidth,g=b[0].offsetHeight;
if(h){h=a;var l=this.getPosition(this.$viewport);a="bottom"==a&&d.bottom+g>l.bottom?"top":"top"==a&&d.top-g<l.top?"bottom":"right"==a&&d.right+k>l.width?"left":"left"==a&&d.left-k<l.left?"right":a;b.removeClass(h).addClass(a)}d=this.getCalculatedOffset(a,d,k,g);this.applyPlacement(d,a);a=function(){var m=c.hoverState;c.$element.trigger("shown.bs."+c.type);c.hoverState=null;"out"==m&&c.leave(c)};e.support.transition&&this.$tip.hasClass("fade")?b.one("bsTransitionEnd",a).emulateTransitionEnd(f.TRANSITION_DURATION):
a()}}};f.prototype.applyPlacement=function(b,a){var c=this.tip(),d=c[0].offsetWidth,h=c[0].offsetHeight,k=parseInt(c.css("margin-top"),10),g=parseInt(c.css("margin-left"),10);isNaN(k)&&(k=0);isNaN(g)&&(g=0);b.top+=k;b.left+=g;e.offset.setOffset(c[0],e.extend({using:function(m){c.css({top:Math.round(m.top),left:Math.round(m.left)})}},b),0);c.addClass("in");k=c[0].offsetWidth;g=c[0].offsetHeight;"top"==a&&g!=h&&(b.top=b.top+h-g);var l=this.getViewportAdjustedDelta(a,b,k,g);l.left?b.left+=l.left:b.top+=
l.top;d=(a=/top|bottom/.test(a))?2*l.left-d+k:2*l.top-h+g;h=a?"offsetWidth":"offsetHeight";c.offset(b);this.replaceArrow(d,c[0][h],a)};f.prototype.replaceArrow=function(b,a,c){this.arrow().css(c?"left":"top",50*(1-b/a)+"%").css(c?"top":"left","")};f.prototype.setContent=function(){var b=this.tip(),a=this.getTitle();this.options.html?(this.options.sanitize&&(a=p(a,this.options.whiteList,this.options.sanitizeFn)),b.find(".tooltip-inner").html(a)):b.find(".tooltip-inner").text(a);b.removeClass("fade in top bottom left right")};
f.prototype.hide=function(b){function a(){"in"!=c.hoverState&&d.detach();c.$element&&c.$element.removeAttr("aria-describedby").trigger("hidden.bs."+c.type);b&&b()}var c=this,d=e(this.$tip),h=e.Event("hide.bs."+this.type);this.$element.trigger(h);if(!h.isDefaultPrevented())return d.removeClass("in"),e.support.transition&&d.hasClass("fade")?d.one("bsTransitionEnd",a).emulateTransitionEnd(f.TRANSITION_DURATION):a(),this.hoverState=null,this};f.prototype.fixTitle=function(){var b=this.$element;(b.attr("title")||
"string"!=typeof b.attr("data-original-title"))&&b.attr("data-original-title",b.attr("title")||"").attr("title","")};f.prototype.hasContent=function(){return this.getTitle()};f.prototype.getPosition=function(b){b=b||this.$element;var a=b[0],c="BODY"==a.tagName,d=a.getBoundingClientRect();null==d.width&&(d=e.extend({},d,{width:d.right-d.left,height:d.bottom-d.top}));a=window.SVGElement&&a instanceof window.SVGElement;a=c?{top:0,left:0}:a?null:b.offset();b={scroll:c?document.documentElement.scrollTop||
document.body.scrollTop:b.scrollTop()};c=c?{width:e(window).width(),height:e(window).height()}:null;return e.extend({},d,b,c,a)};f.prototype.getCalculatedOffset=function(b,a,c,d){return"bottom"==b?{top:a.top+a.height,left:a.left+a.width/2-c/2}:"top"==b?{top:a.top-d,left:a.left+a.width/2-c/2}:"left"==b?{top:a.top+a.height/2-d/2,left:a.left-c}:{top:a.top+a.height/2-d/2,left:a.left+a.width}};f.prototype.getViewportAdjustedDelta=function(b,a,c,d){var h={top:0,left:0};if(!this.$viewport)return h;var k=
this.options.viewport&&this.options.viewport.padding||0,g=this.getPosition(this.$viewport);/right|left/.test(b)?(c=a.top-k-g.scroll,a=a.top+k-g.scroll+d,c<g.top?h.top=g.top-c:a>g.top+g.height&&(h.top=g.top+g.height-a)):(d=a.left-k,a=a.left+k+c,d<g.left?h.left=g.left-d:a>g.right&&(h.left=g.left+g.width-a));return h};f.prototype.getTitle=function(){var b=this.$element,a=this.options;return b.attr("data-original-title")||("function"==typeof a.title?a.title.call(b[0]):a.title)};f.prototype.getUID=function(b){do b+=
~~(1E6*Math.random());while(document.getElementById(b));return b};f.prototype.tip=function(){if(!this.$tip&&(this.$tip=e(this.options.template),1!=this.$tip.length))throw Error(this.type+" `template` option must consist of exactly 1 top-level element!");return this.$tip};f.prototype.arrow=function(){return this.$arrow=this.$arrow||this.tip().find(".tooltip-arrow")};f.prototype.enable=function(){this.enabled=!0};f.prototype.disable=function(){this.enabled=!1};f.prototype.toggleEnabled=function(){this.enabled=
!this.enabled};f.prototype.toggle=function(b){var a=this;b&&(a=e(b.currentTarget).data("bs."+this.type),a||(a=new this.constructor(b.currentTarget,this.getDelegateOptions()),e(b.currentTarget).data("bs."+this.type,a)));b?(a.inState.click=!a.inState.click,a.isInStateTrue()?a.enter(a):a.leave(a)):a.tip().hasClass("in")?a.leave(a):a.enter(a)};f.prototype.destroy=function(){var b=this;clearTimeout(this.timeout);this.hide(function(){b.$element.off("."+b.type).removeData("bs."+b.type);b.$tip&&b.$tip.detach();
b.$tip=null;b.$arrow=null;b.$viewport=null;b.$element=null})};f.prototype.sanitizeHtml=function(b){return p(b,this.options.whiteList,this.options.sanitizeFn)};var z=e.fn.tooltip;e.fn.tooltip=function(b){return this.each(function(){var a=e(this),c=a.data("bs.tooltip"),d="object"==typeof b&&b;if(c||!/destroy|hide/.test(b))if(c||a.data("bs.tooltip",c=new f(this,d)),"string"==typeof b)c[b]()})};e.fn.tooltip.Constructor=f;e.fn.tooltip.noConflict=function(){e.fn.tooltip=z;return this}}(jQuery);