/**
 *  Copyright 2014-15 by Riccardo Massera (TheCoder4.Eu) and Stephan Rauh (http://www.beyondjava.net).
 *  
 *  This file is part of BootsFaces.
 *  
 *  BootsFaces is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  BootsFaces is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with BootsFaces. If not, see <http://www.gnu.org/licenses/>.
 */

package net.bootsfaces.component.modal;

import java.io.IOException;

import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.context.ResponseWriter;
import javax.faces.render.FacesRenderer;

import net.bootsfaces.render.CoreRenderer;
import net.bootsfaces.render.H;

/** This class generates the HTML code of &lt;b:modal /&gt;. */
@FacesRenderer(componentFamily = "net.bootsfaces.component", rendererType = "net.bootsfaces.component.modal.Modal")
public class ModalRenderer extends CoreRenderer {

	/**
	 * This methods generates the HTML code of the current b:modal.
	 * <code>encodeBegin</code> generates the start of the component. After the,
	 * the JSF framework calls <code>encodeChildren()</code> to generate the
	 * HTML code between the beginning and the end of the component. For
	 * instance, in the case of a panel component the content of the panel is
	 * generated by <code>encodeChildren()</code>. After that,
	 * <code>encodeEnd()</code> is called to generate the rest of the HTML code.
	 * 
	 * @param context
	 *            the FacesContext.
	 * @param component
	 *            the current b:modal.
	 * @throws IOException
	 *             thrown if something goes wrong when writing the HTML code.
	 */
	@Override
	public void encodeBegin(FacesContext context, UIComponent component) throws IOException {
		if (!component.isRendered()) {
			return;
		}
		/*
		 * <div id="myModal" class="modal fade" tabindex="-1" role="dialog"
		 * aria-labelledby="myModalLabel" aria-hidden="true"> <div
		 * class="modal-dialog"> <div class="modal-content"> <div
		 * class="modal-header"> <button type="button" class="close"
		 * data-dismiss="modal" aria-hidden="true">×</button> <h3
		 * id="myModalLabel">Modal header</h3> </div> <div class="modal-body">
		 * <p>One fine body…</p> </div> <div class="modal-footer"> <button
		 * class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
		 * <button class="btn btn-primary">Save changes</button> </div>
		 * </div><!-- /.modal-content --> </div><!-- /.modal-dialog -->
		 * </div><!-- /.modal -->
		 * 
		 */

		ResponseWriter rw = context.getResponseWriter();

		Modal modal = (Modal) component;

		String title = modal.getTitle();
		rw.startElement("div", component); // modal
		rw.writeAttribute("id", component.getClientId(context), "id");

		String styleClasses = "modal" + " fade";
		if (modal.getStyleClass() != null) {
			styleClasses = modal.getStyleClass() + " " + styleClasses;
		}
		if (!modal.isBackdrop()) {
			rw.writeAttribute("data-backdrop", "static", null);
		}

		if (!modal.isCloseOnEscape()) {
			rw.writeAttribute("data-keyboard", "false", null);
		}

		rw.writeAttribute("class", styleClasses, "class");
		if (modal.getStyle() != null) {
			rw.writeAttribute("style", modal.getStyle(), "style");
		}
		rw.writeAttribute("role", "dialog", null);
		rw.writeAttribute("tabindex", "-1", null);
		rw.writeAttribute("aria-labelledby", component.getClientId(context) + "_Label", null);
		rw.writeAttribute("aria-hidden", "true", null);

		rw.startElement("div", component); // modal-dialog
		String modalStyleClass = "modal" + "-dialog";
		if (modal.getSize() != null) {
			modalStyleClass = modalStyleClass + " " + modal.getSize();
		}
		rw.writeAttribute("class", modalStyleClass, "class");

		rw.startElement("div", component); // modal-content
		rw.writeAttribute("class", "modal-content", "class");

		rw.startElement("div", component); // modal-header
		rw.writeAttribute("class", "modal-header", "class");

		if (modal.isClosable()) {
			rw.startElement("button", component);
			rw.writeAttribute("type", "button", "type");
			rw.writeAttribute("class", "close", "class");
			rw.writeAttribute(H.DISMISS, "modal", "data-dismiss");
			rw.write("&times;");
			rw.endElement("button");
		}

		if (title != null) {
			rw.startElement("h4", component);
			rw.writeAttribute("id", component.getClientId(context) + "_Label", "id");
			rw.writeText(title, null);
			rw.endElement("h4");
			rw.startElement("br", component);
			rw.endElement("br");
		}
		rw.endElement("div"); // modal-header

		rw.startElement("div", component); // modal-body
		if (modal.getContentClass() != null)
			rw.writeAttribute("class", "modal-body " + modal.getContentClass(), "class");
		else
			rw.writeAttribute("class", "modal-body", "class");

		if (modal.getContentStyle() != null)
			rw.writeAttribute("style", modal.getContentStyle(), "style");
	}

	/**
	 * This methods generates the HTML code of the current b:modal.
	 * <code>encodeBegin</code> generates the start of the component. After the,
	 * the JSF framework calls <code>encodeChildren()</code> to generate the
	 * HTML code between the beginning and the end of the component. For
	 * instance, in the case of a panel component the content of the panel is
	 * generated by <code>encodeChildren()</code>. After that,
	 * <code>encodeEnd()</code> is called to generate the rest of the HTML code.
	 * 
	 * @param context
	 *            the FacesContext.
	 * @param component
	 *            the current b:modal.
	 * @throws IOException
	 *             thrown if something goes wrong when writing the HTML code.
	 */
	@Override
	public void encodeEnd(FacesContext context, UIComponent component) throws IOException {
		if (!component.isRendered()) {
			return;
		}
		ResponseWriter rw = context.getResponseWriter();

		rw.endElement("div"); // modal-body

		UIComponent foot = component.getFacet("footer");
		if (foot != null) {
			rw.startElement("div", component); // modal-footer
			rw.writeAttribute("class", "modal-footer", "class");
			foot.encodeAll(context);

			rw.endElement("div"); // modal-footer
		}
		rw.endElement("div"); // modal-content
		rw.endElement("div"); // modal-dialog
		rw.endElement("div"); // modal
		initModal(rw, component.getClientId(context));
	}

	private void initModal(ResponseWriter rw, String cId) throws IOException {
		rw.startElement("script", null);
		rw.writeAttribute("id", cId.concat("_js"), null);
		rw.writeAttribute("type", "text/javascript", null);
		rw.write("$(function(){");
		rw.write("$('#CID').modal({ show: false });".replace("CID", escapeClientId(cId)));
		rw.write("});");
		rw.endElement("script");
	}

}
