/**
 *  Copyright 2014-15 by Riccardo Massera (TheCoder4.Eu) and Stephan Rauh (http://www.beyondjava.net).
 *  
 *  This file is part of BootsFaces.
 *  
 *  BootsFaces is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  BootsFaces is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with BootsFaces. If not, see <http://www.gnu.org/licenses/>.
 */

package net.bootsfaces.component.buttonToolbar;

import javax.faces.component.*;
import java.io.IOException;
import java.util.Map;

import javax.faces.context.FacesContext;
import javax.faces.context.ResponseWriter;
import javax.faces.render.FacesRenderer;

import net.bootsfaces.render.A;
import net.bootsfaces.render.CoreRenderer;
import net.bootsfaces.render.Tooltip;

/** This class generates the HTML code of &lt;b:buttonToolbar /&gt;. */
@FacesRenderer(componentFamily = "net.bootsfaces.component", rendererType = "net.bootsfaces.component.buttonToolbar.ButtonToolbar")
public class ButtonToolbarRenderer extends CoreRenderer {

	/**
	 * This methods generates the HTML code of the current b:buttonToolbar.
	 * <code>encodeBegin</code> generates the start of the component. After the,
	 * the JSF framework calls <code>encodeChildren()</code> to generate the
	 * HTML code between the beginning and the end of the component. For
	 * instance, in the case of a panel component the content of the panel is
	 * generated by <code>encodeChildren()</code>. After that,
	 * <code>encodeEnd()</code> is called to generate the rest of the HTML code.
	 * 
	 * @param fc
	 *            the FacesContext.
	 * @param component
	 *            the current b:buttonToolbar.
	 * @throws IOException
	 *             thrown if something goes wrong when writing the HTML code.
	 */
	@Override
	public void encodeBegin(FacesContext fc, UIComponent component) throws IOException {
		if (!component.isRendered()) {
			return;
		}

		ResponseWriter rw = fc.getResponseWriter();
		ButtonToolbar buttonToolbar = (ButtonToolbar) component;

		String pull = buttonToolbar.getPull();

		rw.startElement("div", buttonToolbar);
		rw.writeAttribute("id", component.getClientId(fc), "id");
		Tooltip.generateTooltip(fc, buttonToolbar, rw);
		String styleClasses = "btn-toolbar";
		if (null != buttonToolbar.getStyleClass()) {
			styleClasses += " " + buttonToolbar.getStyleClass();
		}
		if (pull != null && (pull.equals("right") || pull.equals("left"))) {
			rw.writeAttribute("class", styleClasses.concat(" ").concat("pull").concat("-").concat(pull),
					"class");
		} else {
			rw.writeAttribute("class", styleClasses, "class");
		}
		if (null != buttonToolbar.getStyle()) {
			rw.writeAttribute("style", buttonToolbar.getStyle(), "style");
		}

	}

	/**
	 * This methods generates the HTML code of the current b:buttonToolbar.
	 * <code>encodeBegin</code> generates the start of the component. After the,
	 * the JSF framework calls <code>encodeChildren()</code> to generate the
	 * HTML code between the beginning and the end of the component. For
	 * instance, in the case of a panel component the content of the panel is
	 * generated by <code>encodeChildren()</code>. After that,
	 * <code>encodeEnd()</code> is called to generate the rest of the HTML code.
	 * 
	 * @param context
	 *            the FacesContext.
	 * @param component
	 *            the current b:buttonToolbar.
	 * @throws IOException
	 *             thrown if something goes wrong when writing the HTML code.
	 */
	@Override
	public void encodeEnd(FacesContext context, UIComponent component) throws IOException {
		if (!component.isRendered()) {
			return;
		}
		ButtonToolbar buttonToolbar = (ButtonToolbar) component;
		ResponseWriter rw = context.getResponseWriter();
		rw.endElement("div");
		Tooltip.activateTooltips(context, buttonToolbar);
	}
}
